-- ============================================================
-- ETAPA 6E.1
-- SISTEMA ÚNICO DE INCIDENCIAS
-- ============================================================

create type public.incident_status as enum (
  'PENDIENTE',
  'ACEPTADA',
  'RECHAZADA',
  'RESUELTA',
  'CERRADA'
);

create type public.incident_area as enum (
  'MONITOR',
  'COMERCIAL',
  'ADMIN',
  'DEPOSITO'
);

-- ------------------------------------------------------------
-- INCIDENCIA
-- Una sola incidencia durante toda su vida.
-- La derivación cambia area_responsable.
-- ------------------------------------------------------------

create table public.incidents (
  id bigint generated by default as identity primary key,

  estado public.incident_status not null default 'PENDIENTE',

  area_origen public.incident_area not null,
  area_responsable public.incident_area not null,

  creada_por uuid not null
    references public.profiles(id),

  responsable_usuario_id uuid
    references public.profiles(id),

  order_id bigint
    references public.orders(id),

  delivery_sheet_id bigint
    references public.delivery_sheets(id),

  tipo text not null,
  detalle text not null,

  motivo_rechazo text,
  resolucion text,

  created_at timestamptz not null default now(),
  accepted_at timestamptz,
  resolved_at timestamptz,
  closed_at timestamptz,
  updated_at timestamptz not null default now(),

  constraint incidents_detalle_no_vacio
    check (length(trim(detalle)) > 0),

  constraint incidents_tipo_no_vacio
    check (length(trim(tipo)) > 0),

  constraint incidents_tiene_objeto
    check (
      order_id is not null
      or delivery_sheet_id is not null
    ),

  constraint incidents_rechazo_con_motivo
    check (
      estado <> 'RECHAZADA'
      or (
        motivo_rechazo is not null
        and length(trim(motivo_rechazo)) > 0
      )
    ),

  constraint incidents_resuelta_con_detalle
    check (
      estado <> 'RESUELTA'
      or (
        resolucion is not null
        and length(trim(resolucion)) > 0
      )
    )
);

create index incidents_order_idx
on public.incidents(order_id);

create index incidents_delivery_sheet_idx
on public.incidents(delivery_sheet_id);

create index incidents_responsable_estado_idx
on public.incidents(area_responsable, estado);


-- ------------------------------------------------------------
-- HISTORIAL
-- Nunca se sobreescribe la historia de la incidencia.
-- ------------------------------------------------------------

create table public.incident_history (
  id bigint generated by default as identity primary key,

  incident_id bigint not null
    references public.incidents(id),

  accion text not null,

  estado_anterior public.incident_status,
  estado_nuevo public.incident_status,

  area_anterior public.incident_area,
  area_nueva public.incident_area,

  realizado_por uuid not null
    references public.profiles(id),

  detalle text,

  created_at timestamptz not null default now(),

  constraint incident_history_accion_no_vacia
    check (length(trim(accion)) > 0)
);

create index incident_history_incident_idx
on public.incident_history(incident_id, created_at);


-- ------------------------------------------------------------
-- REGISTRAR AUTOMÁTICAMENTE LA CREACIÓN
-- ------------------------------------------------------------

create or replace function public.log_incident_creation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.incident_history (
    incident_id,
    accion,
    estado_nuevo,
    area_nueva,
    realizado_por,
    detalle
  )
  values (
    new.id,
    'CREADA',
    new.estado,
    new.area_responsable,
    new.creada_por,
    new.detalle
  );

  return new;
end;
$$;

create trigger trg_log_incident_creation
after insert
on public.incidents
for each row
execute function public.log_incident_creation();


-- ------------------------------------------------------------
-- NO BORRADO
-- Incidencias e historial forman parte de la trazabilidad.
-- ------------------------------------------------------------

create or replace function public.prevent_incident_delete()
returns trigger
language plpgsql
as $$
begin
  raise exception 'Las incidencias y su historial no pueden eliminarse';
end;
$$;

create trigger trg_prevent_incident_delete
before delete on public.incidents
for each row
execute function public.prevent_incident_delete();

create trigger trg_prevent_incident_history_delete
before delete on public.incident_history
for each row
execute function public.prevent_incident_delete();


-- ------------------------------------------------------------
-- RLS
-- En esta primera etapa damos lectura según estructura funcional.
-- Las modificaciones se harán después mediante RPC controladas.
-- ------------------------------------------------------------

alter table public.incidents enable row level security;
alter table public.incident_history enable row level security;


-- ADMIN ve todas.

create policy incidents_admin_select
on public.incidents
for select
to authenticated
using (public.is_admin());


create policy incident_history_admin_select
on public.incident_history
for select
to authenticated
using (public.is_admin());


-- Usuario creador puede ver su incidencia.

create policy incidents_creator_select
on public.incidents
for select
to authenticated
using (
  public.is_active_user()
  and creada_por = auth.uid()
);


-- Responsable individual puede verla si fue asignada a él.

create policy incidents_responsible_user_select
on public.incidents
for select
to authenticated
using (
  public.is_active_user()
  and responsable_usuario_id = auth.uid()
);


-- Historial visible si el usuario puede ver la incidencia.

create policy incident_history_visible
on public.incident_history
for select
to authenticated
using (
  exists (
    select 1
    from public.incidents i
    where i.id = incident_history.incident_id
  )
);


-- ------------------------------------------------------------
-- PERMISOS BASE
--
-- Por ahora NO damos UPDATE ni DELETE al cliente.
-- Las acciones se harán mediante RPC en 6E.2.
-- ------------------------------------------------------------

grant select on public.incidents to authenticated;
grant select on public.incident_history to authenticated;

grant usage, select
on sequence public.incidents_id_seq
to authenticated;

grant usage, select
on sequence public.incident_history_id_seq
to authenticated;