-- ============================================================
-- ETAPA 4 - VENDEDOR / PEDIDOS
-- App Gestion Comercial
-- Fecha: 27/09/2026
-- ============================================================
--
-- Principios:
-- 1. El pedido conserva las condiciones comerciales originales.
-- 2. El stock local en 0 NO impide vender.
-- 3. Un producto deshabilitado por Central NO puede venderse.
-- 4. El vendedor no calcula precios manualmente.
-- 5. Los pedidos no se eliminan: conservan historial.
-- 6. Una vez que el pedido entra en operación, Comercial no lo
--    modifica directamente.
-- 7. Las incidencias operativas se incorporarán al circuito
--    correspondiente sin destruir el pedido original.
-- ============================================================


-- ------------------------------------------------------------
-- ESTADOS DEL PEDIDO
-- ------------------------------------------------------------

create type public.order_status as enum (
  'BORRADOR',
  'ALERTA',
  'PENDIENTE',
  'GUARDADO',
  'ATENDIDO',
  'RECHAZADO',
  'ENTREGADO'
);


-- ------------------------------------------------------------
-- PEDIDOS
-- ------------------------------------------------------------

create table public.orders (
  id bigint generated by default as identity primary key,

  client_id bigint not null
    references public.clients(id),

  seller_id uuid not null
    references public.profiles(id),

  estado public.order_status not null default 'BORRADOR',

  fecha_pedido timestamptz not null default now(),

  fecha_entrega date,

  -- Un pedido guardado puede quedar programado para otro día.
  fecha_liberacion timestamptz,

  -- Si existe una alerta de precio, la liberación automática
  -- queda detenida hasta resolverla.
  alerta_precio boolean not null default false,

  observaciones text,

  -- Datos de cierre/rechazo.
  motivo_rechazo text,
  rechazado_at timestamptz,
  rechazado_por uuid references public.profiles(id),

  entregado_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint orders_guardado_fecha_check
    check (
      estado <> 'GUARDADO'
      or fecha_entrega is not null
    ),

  constraint orders_rechazado_motivo_check
    check (
      estado <> 'RECHAZADO'
      or (
        motivo_rechazo is not null
        and btrim(motivo_rechazo) <> ''
      )
    )
);


create index orders_client_id_idx
  on public.orders(client_id);

create index orders_seller_id_idx
  on public.orders(seller_id);

create index orders_estado_idx
  on public.orders(estado);

create index orders_fecha_entrega_idx
  on public.orders(fecha_entrega);


-- ------------------------------------------------------------
-- DETALLE DEL PEDIDO
-- ------------------------------------------------------------
--
-- Además de las FK, guardamos snapshots.
-- De esta manera, si mañana cambia el nombre, presentación,
-- precio o promoción, el pedido histórico NO cambia.
-- ------------------------------------------------------------

create table public.order_items (
  id bigint generated by default as identity primary key,

  order_id bigint not null
    references public.orders(id),

  presentation_id bigint not null
    references public.product_presentations(id),

  cantidad integer not null
    check (cantidad > 0),

  -- Snapshot del producto/presentación.
  product_codigo_snapshot text not null,
  product_nombre_snapshot text not null,
  presentation_codigo_snapshot text not null,
  presentation_nombre_snapshot text not null,

  -- Condición económica original.
  precio_unitario numeric(14,2) not null
    check (precio_unitario >= 0),

  -- Promoción aplicada, si corresponde.
  promotion_id bigint
    references public.promotions(id),

promotion_nombre_snapshot text,

promotion_benefit_type_snapshot public.promotion_benefit_type,

  descuento_porcentaje numeric(7,4)
    check (
      descuento_porcentaje is null
      or (
        descuento_porcentaje >= 0
        and descuento_porcentaje <= 100
      )
    ),

  cantidad_bonificada integer not null default 0
    check (cantidad_bonificada >= 0),

  -- Total correspondiente a las unidades pagas.
  subtotal numeric(16,2) generated always as
    (
      round(
        (
          cantidad * precio_unitario
        ) *
        (
          1 - coalesce(descuento_porcentaje, 0) / 100
        ),
        2
      )
    ) stored,

  created_at timestamptz not null default now()
);


create index order_items_order_id_idx
  on public.order_items(order_id);

create index order_items_presentation_id_idx
  on public.order_items(presentation_id);


-- ------------------------------------------------------------
-- UPDATED_AT PEDIDOS
-- ------------------------------------------------------------

create or replace function public.set_order_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


create trigger trg_orders_updated_at
before update on public.orders
for each row
execute function public.set_order_updated_at();


-- ------------------------------------------------------------
-- NO PERMITIR BORRADO DE PEDIDOS
-- ------------------------------------------------------------

create or replace function public.prevent_order_delete()
returns trigger
language plpgsql
as $$
begin
  raise exception
    'Los pedidos no se eliminan; deben conservarse en el historial'
    using errcode = 'P0001';
end;
$$;


create trigger trg_prevent_order_delete
before delete on public.orders
for each row
execute function public.prevent_order_delete();


-- ------------------------------------------------------------
-- NO PERMITIR BORRADO DE ITEMS
-- ------------------------------------------------------------

-- ------------------------------------------------------------
-- PROTECCIÓN DE ITEMS SEGÚN ESTADO DEL PEDIDO
-- ------------------------------------------------------------
--
-- BORRADOR:
-- permite modificar y eliminar items.
--
-- Una vez confirmado:
-- los items quedan congelados para preservar el historial.
-- ------------------------------------------------------------

create or replace function public.guard_order_item_changes()
returns trigger
language plpgsql
as $$
declare
  v_order_id bigint;
  v_order_status public.order_status;
begin
if tg_op = 'UPDATE' and new.order_id <> old.order_id then
  raise exception
    'Un item no puede trasladarse de un pedido a otro'
    using errcode = 'P0001';
end if;
-- Para cambiar producto, presentación o promoción,
-- el vendedor debe eliminar el item y agregarlo nuevamente.
if tg_op = 'UPDATE' then
  if new.presentation_id is distinct from old.presentation_id
     or new.promotion_id is distinct from old.promotion_id
  then
    raise exception 'Para cambiar producto, presentacion o promocion, elimine el item y agreguelo nuevamente';
  end if;
end if;
-- Si cambia la cantidad, una promocion seleccionada
-- debe seguir cumpliendo su cantidad minima.
if tg_op = 'UPDATE'
   and new.cantidad is distinct from old.cantidad
   and new.promotion_id is not null
then
 if not exists (
  select 1
  from public.promotion_conditions pc
  where pc.promotion_id = new.promotion_id
    and pc.presentation_id = new.presentation_id
    and new.cantidad >= pc.cantidad_minima
) then
  raise exception
    'La nueva cantidad no cumple la cantidad minima de la promocion seleccionada';
end if;

-- Si la promocion es de bonificacion, recalcular los bonificados
-- segun la nueva cantidad y los tramos alcanzados.
if old.promotion_benefit_type_snapshot = 'BONIFICACION' then
  select
    floor(new.cantidad::numeric / pc.cantidad_minima)::integer
      * pb.cantidad_bonificada
  into new.cantidad_bonificada
  from public.promotion_conditions pc
  join public.promotion_benefits pb
    on pb.promotion_id = pc.promotion_id
   and pb.presentation_id = pc.presentation_id
  where pc.promotion_id = new.promotion_id
    and pc.presentation_id = new.presentation_id
    and pb.tipo = 'BONIFICACION';
end if;
end if;
-- Los valores comerciales son calculados por la base y no pueden
-- modificarse manualmente mientras se edita el borrador.
if tg_op = 'UPDATE' then
  if new.precio_unitario is distinct from old.precio_unitario
     or new.product_codigo_snapshot is distinct from old.product_codigo_snapshot
     or new.product_nombre_snapshot is distinct from old.product_nombre_snapshot
     or new.presentation_codigo_snapshot is distinct from old.presentation_codigo_snapshot
     or new.presentation_nombre_snapshot is distinct from old.presentation_nombre_snapshot
     or new.promotion_nombre_snapshot is distinct from old.promotion_nombre_snapshot
     or new.promotion_benefit_type_snapshot is distinct from old.promotion_benefit_type_snapshot
     or new.descuento_porcentaje is distinct from old.descuento_porcentaje
     or (
  new.cantidad_bonificada is distinct from old.cantidad_bonificada
  and not (
    old.promotion_benefit_type_snapshot = 'BONIFICACION'
    and new.cantidad is distinct from old.cantidad
  )
)
  then
    raise exception 'Los valores comerciales del item son calculados por el sistema y no pueden modificarse manualmente';
  end if;
end if;
  v_order_id := case
    when tg_op = 'DELETE' then old.order_id
    else new.order_id
  end;

  select estado
  into v_order_status
  from public.orders
  where id = v_order_id;

  if v_order_status is null then
    raise exception
      'No se encontró el pedido asociado'
      using errcode = 'P0001';
  end if;

  if v_order_status <> 'BORRADOR' then
    raise exception
      'Los productos de un pedido confirmado no pueden modificarse ni eliminarse'
      using errcode = 'P0001';
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;


create trigger trg_guard_order_item_update
before update on public.order_items
for each row
execute function public.guard_order_item_changes();


create trigger trg_guard_order_item_delete
before delete on public.order_items
for each row
execute function public.guard_order_item_changes();
-- ------------------------------------------------------------
-- VALIDACIÓN DEL PRODUCTO AL CARGAR UN ITEM
-- ------------------------------------------------------------
--
-- Regla:
-- - Stock local 0 NO bloquea la venta.
-- - Producto deshabilitado por Central SÍ bloquea la venta.
-- - La presentación debe estar activa.
-- - El producto debe estar activo.
-- ------------------------------------------------------------

create or replace function public.validate_order_item_product()
returns trigger
language plpgsql
as $$
declare
  v_product_id bigint;
  v_product_activo boolean;
  v_disponible_central boolean;
  v_presentation_activa boolean;
begin

  select
    pp.product_id,
    pp.activa,
    p.activo,
    p.disponible_central
  into
    v_product_id,
    v_presentation_activa,
    v_product_activo,
    v_disponible_central
  from public.product_presentations pp
  join public.products p
    on p.id = pp.product_id
  where pp.id = new.presentation_id;

  if v_product_id is null then
    raise exception
      'La presentación seleccionada no existe'
      using errcode = 'P0001';
  end if;

  if not v_presentation_activa then
    raise exception
      'La presentación seleccionada está inactiva'
      using errcode = 'P0001';
  end if;

  if not v_product_activo then
    raise exception
      'El producto seleccionado está inactivo'
      using errcode = 'P0001';
  end if;

  if not v_disponible_central then
    raise exception
      'El producto no está disponible en Central'
      using errcode = 'P0001';
  end if;

  return new;
end;
$$;


create trigger trg_validate_order_item_product
before insert on public.order_items
for each row
execute function public.validate_order_item_product();
-- ------------------------------------------------------------
-- VALIDACIÓN BÁSICA DEL PEDIDO
-- ------------------------------------------------------------
--
-- El vendedor que genera el pedido:
-- - debe existir
-- - debe estar activo
-- - debe tener rol VENDEDOR
--
-- El cliente:
-- - debe existir
-- - debe estar ACTIVO
-- ------------------------------------------------------------

create or replace function public.validate_order()
returns trigger
language plpgsql
security definer
as $$
declare
  v_seller_role public.app_role;
  v_seller_active boolean;
  v_client_status public.client_status;
begin

  select rol, activo
  into v_seller_role, v_seller_active
  from public.profiles
  where id = new.seller_id;

  if v_seller_role is null then
    raise exception
      'El vendedor seleccionado no existe'
      using errcode = 'P0001';
  end if;

  if not v_seller_active then
    raise exception
      'El vendedor seleccionado está inactivo'
      using errcode = 'P0001';
  end if;

  if v_seller_role <> 'VENDEDOR' then
    raise exception
      'El usuario seleccionado no tiene rol VENDEDOR'
      using errcode = 'P0001';
  end if;


  select estado
  into v_client_status
  from public.clients
  where id = new.client_id;

  if v_client_status is null then
    raise exception
      'El cliente seleccionado no existe'
      using errcode = 'P0001';
  end if;

  if v_client_status <> 'ACTIVO' then
    raise exception
      'No se puede generar un pedido para un cliente dado de baja'
      using errcode = 'P0001';
  end if;

  return new;
end;
$$;


create trigger trg_validate_order
before insert on public.orders
for each row
execute function public.validate_order();
-- ------------------------------------------------------------
-- SNAPSHOT Y VALIDACIÓN DEL PRECIO DEL ITEM
-- ------------------------------------------------------------
--
-- El vendedor no define el precio manualmente.
-- La base toma como referencia el precio vigente de la
-- presentación al momento de crear el item.
--
-- El pedido guarda copia de:
-- - código y nombre del producto
-- - código y nombre de la presentación
-- - precio original
--
-- Así los cambios futuros no modifican pedidos históricos.
-- ------------------------------------------------------------

create or replace function public.prepare_order_item()
returns trigger
language plpgsql
as $$
declare
  v_product_codigo text;
  v_product_nombre text;
  v_presentation_codigo text;
  v_presentation_nombre text;
  v_precio numeric(14,2);
begin

  select
    p.codigo,
    p.nombre,
    pp.codigo,
    pp.nombre
  into
    v_product_codigo,
    v_product_nombre,
    v_presentation_codigo,
    v_presentation_nombre
  from public.product_presentations pp
  join public.products p
    on p.id = pp.product_id
  where pp.id = new.presentation_id;

  if v_product_codigo is null then
    raise exception
      'No se pudo identificar el producto de la presentación'
      using errcode = 'P0001';
  end if;


  select pr.precio
  into v_precio
  from public.product_prices pr
  where pr.presentation_id = new.presentation_id
    and pr.vigente_desde <= now()
    and (
      pr.vigente_hasta is null
      or pr.vigente_hasta > now()
    )
  order by pr.vigente_desde desc
  limit 1;


  if v_precio is null then
    raise exception
      'La presentación no tiene un precio vigente'
      using errcode = 'P0001';
  end if;


  new.product_codigo_snapshot := v_product_codigo;
  new.product_nombre_snapshot := v_product_nombre;

  new.presentation_codigo_snapshot := v_presentation_codigo;
  new.presentation_nombre_snapshot := v_presentation_nombre;

  -- El precio lo determina la base.
  -- No se acepta un precio enviado manualmente por el vendedor.
  new.precio_unitario := v_precio;

  return new;
end;
$$;


create trigger trg_prepare_order_item
before insert on public.order_items
for each row
execute function public.prepare_order_item();
-- ------------------------------------------------------------
-- REGLA DE SELECCIÓN DE PROMOCIONES
-- ------------------------------------------------------------
--
-- Si más de una promoción es aplicable:
-- - el sistema muestra las promociones válidas
-- - el VENDEDOR selecciona cuál aplicar
-- - las promociones no se acumulan automáticamente
-- - la base valida que la promoción seleccionada:
--     * esté activa
--     * esté vigente
--     * corresponda a la presentación
--     * cumpla la cantidad mínima
--
-- El vendedor selecciona la promoción.
-- El beneficio económico lo determina la base.
-- ------------------------------------------------------------
-- ------------------------------------------------------------
-- VALIDACIÓN Y APLICACIÓN DE PROMOCIÓN SELECCIONADA
-- ------------------------------------------------------------

create or replace function public.apply_selected_promotion()
returns trigger
language plpgsql
as $$
declare
  v_promotion_nombre text;
  v_benefit_type public.promotion_benefit_type;
  v_precio_especial numeric(14,2);
  v_descuento numeric(5,2);
  v_bonificacion integer;
  v_cantidad_minima integer;
begin

  -- Sin promoción seleccionada, conserva el precio normal.
  if new.promotion_id is null then
    new.promotion_nombre_snapshot := null;
    new.promotion_benefit_type_snapshot := null;
    new.descuento_porcentaje := null;
    new.cantidad_bonificada := 0;
    return new;
  end if;


  -- Validar que la promoción esté activa y vigente.
  select p.nombre
  into v_promotion_nombre
  from public.promotions p
  where p.id = new.promotion_id
    and p.activa = true
    and p.vigente_desde <= now()
    and (
      p.vigente_hasta is null
      or p.vigente_hasta > now()
    );

  if v_promotion_nombre is null then
    raise exception
      'La promoción seleccionada no está activa o vigente'
      using errcode = 'P0001';
  end if;


  -- Validar que esta presentación forme parte de las
  -- condiciones de la promoción.
  select pc.cantidad_minima
  into v_cantidad_minima
  from public.promotion_conditions pc
  where pc.promotion_id = new.promotion_id
    and pc.presentation_id = new.presentation_id;

  if v_cantidad_minima is null then
    raise exception
      'La promoción seleccionada no corresponde a esta presentación'
      using errcode = 'P0001';
  end if;


  if new.cantidad < v_cantidad_minima then
    raise exception
      'La cantidad del pedido no alcanza el mínimo requerido por la promoción'
      using errcode = 'P0001';
  end if;


  -- Obtener el beneficio correspondiente a la presentación.
  select
    pb.tipo,
    pb.precio_especial,
    pb.descuento_porcentaje,
    pb.cantidad_bonificada
  into
    v_benefit_type,
    v_precio_especial,
    v_descuento,
    v_bonificacion
  from public.promotion_benefits pb
  where pb.promotion_id = new.promotion_id
    and pb.presentation_id = new.presentation_id
  limit 1;


  if v_benefit_type is null then
    raise exception
      'La promoción seleccionada no tiene un beneficio válido para esta presentación'
      using errcode = 'P0001';
  end if;


  -- Snapshot de la promoción aplicada.
  new.promotion_nombre_snapshot := v_promotion_nombre;
  new.promotion_benefit_type_snapshot := v_benefit_type;

  -- Aplicar automáticamente el beneficio.
  case v_benefit_type

    when 'PRECIO_ESPECIAL' then
      new.precio_unitario := v_precio_especial;
      new.descuento_porcentaje := null;
      new.cantidad_bonificada := 0;

    when 'DESCUENTO_PORCENTAJE' then
      new.descuento_porcentaje := v_descuento;
      new.cantidad_bonificada := 0;

    when 'BONIFICACION' then
  new.descuento_porcentaje := null;
  new.cantidad_bonificada :=
    floor(new.cantidad::numeric / v_cantidad_minima)::integer
    * v_bonificacion;

  end case;

  return new;
end;
$$;


create trigger trg_z_apply_selected_promotion
before insert on public.order_items
for each row
execute function public.apply_selected_promotion();
-- ------------------------------------------------------------
-- CONFIRMACIÓN DEL PEDIDO
-- ------------------------------------------------------------
--
-- BORRADOR:
-- puede existir sin items y retomarse posteriormente.
--
-- Al pasar de BORRADOR a PENDIENTE:
-- debe existir al menos un item en el pedido.
-- ------------------------------------------------------------

create or replace function public.validate_order_confirmation()
returns trigger
language plpgsql
as $$
declare
  v_condiciones_cambiaron boolean := false;
begin
-- Los datos estructurales del pedido no pueden cambiarse
-- una vez creado el BORRADOR.
if new.seller_id is distinct from old.seller_id then
  raise exception
    'No se puede cambiar el vendedor de un pedido existente'
    using errcode = 'P0001';
end if;

if new.client_id is distinct from old.client_id then
  raise exception
    'No se puede cambiar el cliente de un pedido existente'
    using errcode = 'P0001';
end if;

if new.fecha_pedido is distinct from old.fecha_pedido then
  raise exception
    'No se puede modificar la fecha original del pedido'
    using errcode = 'P0001';
end if;
-- Estos campos son controlados por el sistema y no pueden
-- modificarse manualmente desde un BORRADOR.
if old.estado = 'BORRADOR' then

  if new.fecha_liberacion is distinct from old.fecha_liberacion
     or new.motivo_rechazo is distinct from old.motivo_rechazo
     or new.rechazado_at is distinct from old.rechazado_at
     or new.rechazado_por is distinct from old.rechazado_por
     or new.entregado_at is distinct from old.entregado_at
  then
    raise exception
      'Los campos operativos del pedido son controlados por el sistema'
      using errcode = 'P0001';
  end if;

  -- La alerta es controlada exclusivamente por el sistema.
-- Más abajo, este mismo trigger podrá activarla si detecta
-- un cambio en las condiciones comerciales.
if new.alerta_precio is distinct from old.alerta_precio then
  raise exception
    'La alerta del pedido es controlada por el sistema'
    using errcode = 'P0001';
end if;

end if;
  if old.estado = 'BORRADOR'
     and new.estado <> 'BORRADOR'
     and new.estado <> 'PENDIENTE'
  then
    raise exception
      'Un pedido en borrador solo puede confirmarse pasando a PENDIENTE'
      using errcode = 'P0001';
  end if;
  if old.estado = 'BORRADOR'
     and new.estado = 'PENDIENTE'
     and not exists (
       select 1
       from public.order_items oi
       where oi.order_id = new.id
     )
  then
    raise exception
      'No se puede confirmar un pedido sin productos'
      using errcode = 'P0001';
  end if;
  -- Al confirmar, ningun producto puede estar deshabilitado en Central.
if old.estado = 'BORRADOR'
   and new.estado = 'PENDIENTE'
   and exists (
     select 1
     from public.order_items oi
     join public.product_presentations pp
       on pp.id = oi.presentation_id
     join public.products p
       on p.id = pp.product_id
     where oi.order_id = new.id
       and (
         p.activo = false
         or p.disponible_central = false
         or pp.activa = false
       )
   )
then
  raise exception
    'No se puede confirmar el pedido porque contiene un producto no disponible en Central'
    using errcode = 'P0001';
end if;
  if old.estado = 'BORRADOR'
     and new.estado = 'PENDIENTE'
     and exists (
       select 1
       from public.order_items oi
       where oi.order_id = new.id
         and (
  oi.promotion_benefit_type_snapshot is distinct from 'PRECIO_ESPECIAL'
and oi.precio_unitario is distinct from (
    select pr.precio
    from public.product_prices pr
    where pr.presentation_id = oi.presentation_id
      and pr.vigente_desde <= now()
      and (
        pr.vigente_hasta is null
        or pr.vigente_hasta > now()
      )
    
           order by pr.vigente_desde desc
           limit 1
         )
     )
     )
  then
    v_condiciones_cambiaron := true;
  end if;
    if old.estado = 'BORRADOR'
     and new.estado = 'PENDIENTE'
     and exists (
       select 1
       from public.order_items oi
       left join public.promotions p
         on p.id = oi.promotion_id
       left join public.promotion_conditions pc
         on pc.promotion_id = oi.promotion_id
        and pc.presentation_id = oi.presentation_id
       left join public.promotion_benefits pb
         on pb.promotion_id = oi.promotion_id
        and pb.presentation_id = oi.presentation_id
       where oi.order_id = new.id
         and oi.promotion_id is not null
         and (
           p.id is null
           or p.activa = false
           or p.vigente_desde > now()
           or (p.vigente_hasta is not null and p.vigente_hasta <= now())
           or pc.promotion_id is null
           or oi.cantidad < pc.cantidad_minima
           or pb.tipo is distinct from oi.promotion_benefit_type_snapshot
or (
  pb.tipo = 'PRECIO_ESPECIAL'
  and oi.precio_unitario is distinct from pb.precio_especial
)
or (
  pb.tipo = 'DESCUENTO_PORCENTAJE'
  and oi.descuento_porcentaje is distinct from pb.descuento_porcentaje
)
or (
  pb.tipo = 'BONIFICACION'
  and oi.cantidad_bonificada is distinct from (
  floor(oi.cantidad::numeric / pc.cantidad_minima)::integer
  * pb.cantidad_bonificada
)
)
         )
     )
  then
    v_condiciones_cambiaron := true;
  end if;
    if old.estado = 'BORRADOR'
     and new.estado = 'PENDIENTE'
     and v_condiciones_cambiaron
  then
    new.estado := 'ALERTA';
    new.alerta_precio := true;
  end if;
  return new;
end;
$$;


create trigger trg_validate_order_confirmation
before update on public.orders
for each row
execute function public.validate_order_confirmation();
-- ------------------------------------------------------------
-- SEGURIDAD RLS - PEDIDOS
-- ------------------------------------------------------------

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
-- VENDEDOR: puede ver sus propios pedidos.
create policy orders_vendedor_select
on public.orders
for select
to authenticated
using (
  seller_id = auth.uid()
);

-- VENDEDOR: puede crear solamente pedidos propios.
create policy orders_vendedor_insert
on public.orders
for insert
to authenticated
with check (
  seller_id = auth.uid()
  and estado = 'BORRADOR'
);
-- VENDEDOR: puede actualizar sus propios pedidos
-- mientras el flujo parte de su pedido.
-- VENDEDOR: puede actualizar únicamente sus propios pedidos
-- mientras todavía están en BORRADOR.
-- La confirmación BORRADOR -> PENDIENTE también parte de un BORRADOR;
-- el trigger de confirmación puede convertirlo en ALERTA.
create policy orders_vendedor_update
on public.orders
for update
to authenticated
using (
  seller_id = auth.uid()
  and estado = 'BORRADOR'
)
with check (
  seller_id = auth.uid()
  and estado in ('BORRADOR', 'PENDIENTE', 'ALERTA')
);
-- VENDEDOR: puede ver los items de sus propios pedidos.
create policy order_items_vendedor_select
on public.order_items
for select
to authenticated
using (
  exists (
    select 1
    from public.orders o
    where o.id = order_items.order_id
      and o.seller_id = auth.uid()
  )
);
-- VENDEDOR: puede agregar items solamente a sus propios BORRADORES.
create policy order_items_vendedor_insert
on public.order_items
for insert
to authenticated
with check (
  exists (
    select 1
    from public.orders o
    where o.id = order_items.order_id
      and o.seller_id = auth.uid()
      and o.estado = 'BORRADOR'
  )
);
-- VENDEDOR: puede modificar items solamente de sus propios BORRADORES.
create policy order_items_vendedor_update
on public.order_items
for update
to authenticated
using (
  exists (
    select 1
    from public.orders o
    where o.id = order_items.order_id
      and o.seller_id = auth.uid()
      and o.estado = 'BORRADOR'
  )
)
with check (
  exists (
    select 1
    from public.orders o
    where o.id = order_items.order_id
      and o.seller_id = auth.uid()
      and o.estado = 'BORRADOR'
  )
);

-- VENDEDOR: puede eliminar items solamente de sus propios BORRADORES.
create policy order_items_vendedor_delete
on public.order_items
for delete
to authenticated
using (
  exists (
    select 1
    from public.orders o
    where o.id = order_items.order_id
      and o.seller_id = auth.uid()
      and o.estado = 'BORRADOR'
  )
);
-- ------------------------------------------------------------
-- ADMIN: acceso total a PEDIDOS e ITEMS
-- ------------------------------------------------------------

create policy orders_admin_all
on public.orders
for all
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.rol = 'ADMIN'
      and p.activo = true
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.rol = 'ADMIN'
      and p.activo = true
  )
);

create policy order_items_admin_all
on public.order_items
for all
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.rol = 'ADMIN'
      and p.activo = true
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.rol = 'ADMIN'
      and p.activo = true
  )
);
-- ------------------------------------------------------------
-- PERMISOS BASE PARA USUARIOS AUTENTICADOS
-- RLS determina después qué filas puede operar cada usuario.
-- ------------------------------------------------------------

grant select, insert, update, delete
on table public.orders
to authenticated;

grant select, insert, update, delete
on table public.order_items
to authenticated;